dim: 64

epochs: 10
convergence_threshold: 2

alpha_schedule:
  - 
    - 1
    - 2
    - 2
    - 301
  -
    - 0.01
    - 0.01
    - 0.001
    - 0.001

num_walks: 20     # 3m: 50, 300k: 20
walk_length: 30   # 3m: 15, 300k: 30
window: 3
p: 1.0
q: 10.0
