# data_root: /media/xreco/DEV/xiran/data/dgl_gnn_link_pred/graph/xbox300k
# results_root: /media/xreco/DEV/xiran/data/new-n2v-64/debug

# data_root: /media/xreco/DEV/xinhao/xbox_gamepass_wkflow/xfriend_auto_pipeline/output/instances_3m_und_e0_dl3_du100_hop4
# results_root: /media/xreco/DEV/xiran/data/3m_und_e0_dl3_du100_hop4/n2v-test

dim: 64

epochs: 50
convergence_threshold: 1

alpha_schedule:
  - 
    - 1
    - 2
    - 2
    - 301
  -
    - 0.01
    - 0.01
    - 0.001
    - 0.001

num_walks: 20     # 3m: 50, 300k: 20
walk_length: 30   # 3m: 15, 300k: 30
window: 3
p: 1.0
q: 10.0
